---
apiVersion: apps/v1
kind: Deplyment
metadata:
  name: web-backend
  labels:
    app: api
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api

  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: python-api
          image: python:3.11-slim
          ports:
            - containerPort: 8000
